// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePaymentInput struct {
	Amount      float64 `json:"amount"`
	Currency    string  `json:"currency"`
	Description string  `json:"description"`
}

type Mutation struct {
}

type Query struct {
}

type UpdatePaymentInput struct {
	ID          string         `json:"id"`
	Amount      *float64       `json:"amount,omitempty"`
	Currency    *string        `json:"currency,omitempty"`
	Description *string        `json:"description,omitempty"`
	Status      *PaymentStatus `json:"status,omitempty"`
}
